name: Bankey
options:
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: en
targets:
  Bankey:
    type: application
    platform: iOS
    deploymentTarget: '13.0'
    sources: [Bankey]
