name: Bankey
options:
  bundleIdPrefix: com.devmeist3r
  deploymentTarget:
    iOS: 15.2
targets:
  Bankey:
    type: application
    platform: iOS
    sources:
      - path: Bankey
  BankeyUnitTests:
    type: bundle.unit-test
    platform: iOS
    dependecies:
      - target: Bankey
    sources:
      - path: BankeyUnitTests
