name: Bankey
options:
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: en
targets:
  Bankey:
    type: application
    platform: iOS
    deploymentTarget: '15.2'
    sources: [Bankey]
  BankeyUnitTests:
    type: bundle.unit-test
    platform: iOS
    dependecies:
      - target: Bankey
    sources:
      - path: BankeyUnitTests
